"""
Google Reviews source (stub with realistic sample data).
Simulates Google Maps reviews for Karma Group resort properties.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class GoogleReviewsSource(BaseSource):
    """Returns realistic sample Google Maps reviews for Karma Group resorts."""

    @property
    def source_name(self) -> str:
        return "Google Reviews"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info(
            "GoogleReviewsSource: loaded %d sample reviews", len(self._reviews)
        )
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "One of the most spectacular resort locations I've ever visited. The private beach accessible via an inclinator is phenomenal. Staff are warm and professional. The villas are spacious and well-maintained. Used the Karma Subito app for pre-check-in and it saved us at least 20 minutes at reception.",
        "review_date": "2026-07-02T11:30:00",
        "reviewer": "Alex Mitchell",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 24,
        "source_review_id": "gr_001",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 2,
        "review_text": "Beautiful property marred by aggressive timeshare sales tactics. We were approached THREE times during our 4-night stay about attending a membership presentation. When we finally attended to get them to stop, it was a 2.5-hour ordeal. The app kept sending membership upgrade push notifications even after checkout. Unsubscribing doesn't work.",
        "review_date": "2026-06-22T15:45:00",
        "reviewer": "Claire Thompson",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 45,
        "source_review_id": "gr_002",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Royal Jimbaran",
        "rating": 5,
        "review_text": "We stayed in the Presidential Villa and it was absolutely incredible. Private pool, outdoor rain shower, and a living area bigger than our apartment back home. The butler service was impeccable — Made (our butler) arranged a private Balinese cooking class that was the highlight of the trip. Exceptional value through our membership points.",
        "review_date": "2026-06-10T08:22:00",
        "reviewer": "Priyanka Sharma",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 18,
        "source_review_id": "gr_003",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Rottnest",
        "rating": 4,
        "review_text": "Unique island experience with eco-friendly accommodation. The quokkas are adorable and the beaches are pristine. The glamping tents are surprisingly comfortable with proper beds and en-suite bathrooms. Only issue: the app didn't load the island map offline and there's no wifi signal in most of the island. Need offline mode!",
        "review_date": "2026-05-28T13:50:00",
        "reviewer": "Jason Lee",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 12,
        "source_review_id": "gr_004",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Royal Sanur",
        "rating": 3,
        "review_text": "Decent resort but not luxury by current standards. The rooms feel a bit dated — the furniture and fixtures could use a refresh. The pool is nice and the beach location is great. Staff are friendly. The app's concierge chatbot kept recommending restaurants that were permanently closed. Not helpful.",
        "review_date": "2026-05-15T17:08:00",
        "reviewer": "Michelle Wong",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 9,
        "source_review_id": "gr_005",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Celebrating our silver wedding anniversary here was the best decision we ever made. The sunset dinner on the cliff was unforgettable. The spa couples treatment was heavenly. The staff arranged a surprise flower arrangement and champagne in our villa. This is what 25 years of love deserves!",
        "review_date": "2026-04-30T19:15:00",
        "reviewer": "Robert & Linda Harrison",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 31,
        "source_review_id": "gr_006",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Salak",
        "rating": 5,
        "review_text": "The hot springs surrounded by tropical forest are magical. Perfect weekend getaway from Jakarta. The colonial-era buildings have been beautifully restored. The tea plantation tour was a lovely touch. Staff are incredibly attentive. Already booked our next visit through the Karma Subito app — surprisingly smooth this time.",
        "review_date": "2026-04-18T10:40:00",
        "reviewer": "Denny Pratama",
        "country": "ID",
        "language": "en",
        "app_version": None,
        "helpful_count": 15,
        "source_review_id": "gr_007",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Baviera",
        "rating": 4,
        "review_text": "Charming alpine hotel with stunning Dolomite views. The restaurant serves excellent local South Tyrolean cuisine. Rooms are cozy and warm. The ski shuttle service was convenient. Deducting one star because the app showed availability for our preferred room type but when we arrived, we were given a different (smaller) room.",
        "review_date": "2026-04-05T14:25:00",
        "reviewer": "Stefan Müller",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 7,
        "source_review_id": "gr_008",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "Worst customer service I've ever experienced at a so-called luxury resort. The payment terminal at checkout charged my card in the wrong currency and I was hit with a $150 conversion fee. When I tried to dispute through the app, the chatbot couldn't help and the 'contact support' form returned a 404 error. Had to dispute with my bank. Shameful.",
        "review_date": "2026-03-22T21:55:00",
        "reviewer": "Amanda Foster",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 58,
        "source_review_id": "gr_009",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Royal Haathi Mahal",
        "rating": 5,
        "review_text": "Hidden paradise in South Goa! The elephant-themed architecture is charming and the grounds are lush and green. The pool complex is one of the best in Goa. The buffet breakfast has an incredible spread of Indian and continental options. Our kids loved the kids' club. Will definitely return next year.",
        "review_date": "2026-03-08T09:12:00",
        "reviewer": "Anand Krishnan",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 22,
        "source_review_id": "gr_010",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Minoan",
        "rating": 4,
        "review_text": "Beautiful property on the north coast of Crete. The suites are spacious with full kitchens. The pool area is well-maintained and never felt crowded. Great base for exploring Chania and Rethymno. The app should have better integration with local tour operators — I had to book all excursions separately through WhatsApp.",
        "review_date": "2026-02-22T16:30:00",
        "reviewer": "Sarah Kowalski",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 8,
        "source_review_id": "gr_011",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "The resort needs major renovation. Our villa had peeling paint, a leaking shower, and ant infestations. For $400/night this is completely unacceptable. Management's response was 'we'll look into it' with no actual resolution. The app photos are clearly from years ago and don't reflect the current state of the property. Misleading advertising.",
        "review_date": "2026-02-08T12:42:00",
        "reviewer": "David Chen",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 72,
        "source_review_id": "gr_012",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Song Hoai",
        "rating": 5,
        "review_text": "Absolutely fell in love with this boutique property in the heart of Hoi An. The lantern-lit courtyard is pure magic, especially at night. Rooms are beautifully decorated with local Vietnamese art. The rooftop bar has incredible views of the Thu Bon River. Walking distance to everything. Staff arranged a private boat trip to the Cham Islands that was unforgettable.",
        "review_date": "2026-01-25T07:55:00",
        "reviewer": "Emma Richardson",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 19,
        "source_review_id": "gr_013",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "The membership programme is confusing. Different tier levels, different point calculations, blackout dates that aren't clearly shown in the app. I spent 30 minutes trying to figure out if I had enough points for a 3-night stay and ended up calling customer service. They need a simple points calculator in the app. Marriott Bonvoy makes this SO much easier.",
        "review_date": "2026-01-10T18:20:00",
        "reviewer": "Kevin Murphy",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 28,
        "source_review_id": "gr_014",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Third visit and it's still my favorite resort in the world. The private beach, Di Mare restaurant, the spa — everything is consistently excellent. The new wellness programme is a great addition. Staff remembered us from our last visit two years ago. That kind of personal touch is rare and priceless.",
        "review_date": "2025-12-28T11:08:00",
        "reviewer": "Jess & Mark Taylor",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 14,
        "source_review_id": "gr_015",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "The app crashed 4 times while I was trying to enter payment details. Each time I had to re-enter my credit card number from scratch because it doesn't save payment methods. In 2025! Even basic e-commerce sites save your card. Also, the security code verification SMS never arrived so I couldn't complete the booking at all.",
        "review_date": "2025-12-15T20:35:00",
        "reviewer": "Raj Mehta",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 33,
        "source_review_id": "gr_016",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Royal Jimbaran",
        "rating": 4,
        "review_text": "Excellent resort with stunning sunset views from the infinity pool. The Jimbaran seafood dinner on the beach was a highlight. Rooms are spacious and the kitchen facilities are a nice bonus. Lost one star because the wifi was unreliable and the app-based room service ordering system was completely down during our stay.",
        "review_date": "2025-11-30T13:48:00",
        "reviewer": "Lisa Patterson",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 6,
        "source_review_id": "gr_017",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "We hosted our daughter's destination wedding at Karma Kandara and it was beyond perfect. The events team handled every detail flawlessly. The cliff-top ceremony location had our guests in tears. The reception at Di Mare was elegant and the food was outstanding. Thank you Karma for making our family's dream come true!",
        "review_date": "2025-11-12T09:25:00",
        "reviewer": "Margaret O'Brien",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 42,
        "source_review_id": "gr_018",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "Average experience overall. The property was fine but nothing special for the price. I stayed at a similar Airbnb next door for half the cost last year. The Karma membership 'benefits' mostly consist of discounts on overpriced services. The app's loyalty dashboard is confusing and my points balance never seems accurate.",
        "review_date": "2025-10-25T16:12:00",
        "reviewer": "Tony Williams",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 15,
        "source_review_id": "gr_019",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Cay Tre",
        "rating": 4,
        "review_text": "Lovely beachfront resort in Phu Quoc. The rooms are clean and comfortable with beautiful sea views. The pool is surrounded by palm trees and feels very tropical. The seafood BBQ night is a must. Staff go out of their way to make you feel welcome. Would love the app to add Vietnamese Dong pricing alongside USD.",
        "review_date": "2025-10-08T10:55:00",
        "reviewer": "Michael Barnes",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 5,
        "source_review_id": "gr_020",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "Booked through the app for specific dates and received a confirmation email. When we arrived, they had no record of our booking! The app confirmation was apparently a 'system error'. They scrambled to find us a room but we ended up in a much lower category than what we paid for. No compensation offered. Will never book through this app again.",
        "review_date": "2025-09-20T22:18:00",
        "reviewer": "Sue & Peter Clarke",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 88,
        "source_review_id": "gr_021",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Royal Haathi Mahal",
        "rating": 5,
        "review_text": "We visited during Diwali and the resort was decorated beautifully. The festive dinner was a grand affair with traditional music and dance performances. The kids participated in rangoli making and absolutely loved it. The Goan countryside setting is peaceful and the pool complex is world-class. Best family Diwali celebration ever!",
        "review_date": "2025-09-05T07:40:00",
        "reviewer": "Deepika Nair",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 26,
        "source_review_id": "gr_022",
    },
    {
        "source": "Google Reviews",
        "app_name": "Karma Kandara",
        "rating": 4,
        "review_text": "Gorgeous property with a few operational hiccups. The sunset at Di Mare restaurant is worth the trip alone. The beach club is fantastic. Room could have been cleaner on arrival but was sorted quickly after flagging. Feature request for the app: let guests rate individual services (spa, restaurant, room) separately, not just the overall stay.",
        "review_date": "2025-08-18T14:30:00",
        "reviewer": "Tom Andrews",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 10,
        "source_review_id": "gr_023",
    },
]
