"""
Reddit review source (stub with realistic sample data).
Simulates posts from r/travel, r/luxurytravel, and other subreddits about Karma resorts.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class RedditSource(BaseSource):
    """Returns realistic sample Reddit posts/comments about Karma Group."""

    @property
    def source_name(self) -> str:
        return "Reddit"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info("RedditSource: loaded %d sample reviews", len(self._reviews))
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/luxurytravel] Just got back from Karma Kandara in Bali and WOW. The cliff-top infinity pool is even more stunning than the photos. We paid with points from our Karma membership and the value was insane. If you're considering a luxury timeshare that actually delivers, this is it.",
        "review_date": "2026-06-30T22:15:00",
        "reviewer": "u/bali_or_bust",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 187,
        "source_review_id": "rd_001",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 1,
        "review_text": "[r/travel] PSA: Karma Subito app is terrible. Tried to book a resort stay and the app crashed 3 times during checkout. Lost my selected dates, room preferences, everything. Ended up booking through their website instead. For a 'luxury' brand, their tech is embarrassingly bad. Even Airbnb's app from 5 years ago was better than this.",
        "review_date": "2026-06-20T16:42:00",
        "reviewer": "u/techie_traveler_99",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 342,
        "source_review_id": "rd_002",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "[r/travel] Karma Rottnest Island review: Really unique experience. The eco-glamping setup is gorgeous and the quokkas are everywhere (in the best way). Food was great, staff were friendly. Only ding is the ferry scheduling — the app doesn't integrate with ferry times so you have to plan separately.",
        "review_date": "2026-06-08T09:30:00",
        "reviewer": "u/perth_weekender",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 95,
        "source_review_id": "rd_003",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "[r/personalfinance] WARNING about Karma Group timeshare sales. My parents got roped into a 'free holiday presentation' and ended up signing a $15k membership. The cancellation process is nearly impossible — the app shows no cancellation option and the phone line puts you on hold for 45+ minutes. They're now disputing through their credit card company.",
        "review_date": "2026-05-25T14:18:00",
        "reviewer": "u/protecting_parents",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 521,
        "source_review_id": "rd_004",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/luxurytravel] Unpopular opinion: Karma Group membership is actually worth it if you travel 2-3 times a year. We've been members for 4 years and have stayed at properties in Bali, Vietnam, Greece, and India. The points system is generous and the resorts are consistently beautiful. Not every timeshare is a scam.",
        "review_date": "2026-05-12T11:05:00",
        "reviewer": "u/frequent_karma_flyer",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 234,
        "source_review_id": "rd_005",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 3,
        "review_text": "[r/androidapps] Anyone else having issues with Karma Subito? The app takes 20+ seconds to load on my Pixel 8 Pro. Images are blurry thumbnails that never load to full resolution. The search function returns random results — I searched 'Greece' and got Goa properties. It's like they built it in 2015 and never updated the performance.",
        "review_date": "2026-04-28T20:33:00",
        "reviewer": "u/android_quality_police",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 156,
        "source_review_id": "rd_006",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/honeymoon] Just planned our entire honeymoon through Karma Group. 5 nights at Karma Kandara + 3 nights at Karma Song Hoai in Hoi An. The membership concierge helped arrange private dinners, spa treatments, and a sunrise yacht trip. Total cost with membership points was about 40% less than booking comparable hotels independently.",
        "review_date": "2026-04-15T13:20:00",
        "reviewer": "u/honeymoon_planner_2026",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 178,
        "source_review_id": "rd_007",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[r/UXDesign] I work in UX and the Karma Subito app is a masterclass in what NOT to do. The booking flow has 9 screens(!), the country picker is an unsearchable alphabetical dropdown, form validation happens only on submit so you lose everything if one field is wrong, and there's no progress indicator. Wish it was as polished as the Marriott Bonvoy app.",
        "review_date": "2026-04-02T17:45:00",
        "reviewer": "u/ux_designerlife",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 445,
        "source_review_id": "rd_008",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "[r/Bali] Stayed at Karma Royal Jimbaran for 10 nights. The private villas are incredible and the staff treat you like royalty. The location is a bit far from the action in Seminyak but the resort has enough to keep you busy. Pro tip: book the villa with the outdoor bathtub — you won't regret it.",
        "review_date": "2026-03-18T08:50:00",
        "reviewer": "u/bali_regular",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "rd_009",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[r/iphone] The Karma Subito app doesn't support Face ID and makes you type your password every. single. time. In 2026! Also no dark mode, no widget support, and the notifications are completely broken. I get push notifications for promotions at 3am but never got my check-in reminder. Club Mahindra has a way better app experience.",
        "review_date": "2026-03-05T22:10:00",
        "reviewer": "u/apple_user_complaints",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 203,
        "source_review_id": "rd_010",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/travel] Just want to give a shoutout to the staff at Karma Salak near Bogor. The hot springs in the middle of a tropical forest are surreal. Our butler Wayan remembered that my daughter is vegetarian from our last visit 2 years ago and had special meals prepared before we even asked. THAT is luxury service.",
        "review_date": "2026-02-20T12:35:00",
        "reviewer": "u/jakarta_weekender",
        "country": "ID",
        "language": "en",
        "app_version": None,
        "helpful_count": 167,
        "source_review_id": "rd_011",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[r/timeshare] Honest review of Karma Group membership after 3 years: PROS — beautiful properties, good points system, staff are amazing. CONS — aggressive upselling, app is buggy, customer service via email is painfully slow (avg 5 business days for a response). Would I buy again? Probably yes, but I'd negotiate harder on the price.",
        "review_date": "2026-02-05T15:48:00",
        "reviewer": "u/timeshare_realist",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 312,
        "source_review_id": "rd_012",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 3,
        "review_text": "[r/travel] Feature request megathread for Karma Subito app: 1) OFFLINE MODE for accessing bookings without wifi, 2) Digital wallet for membership cards, 3) In-app room service ordering, 4) AI concierge that actually works, 5) Better search with filters (dates, price, property type), 6) Family profiles to save traveler details. Tagging @KarmaGroup in hopes they see this.",
        "review_date": "2026-01-22T19:25:00",
        "reviewer": "u/karma_app_improvement",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 678,
        "source_review_id": "rd_013",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/luxurytravel] The Karma Minoan in Crete is the best-kept secret in the Mediterranean. We stayed in August (peak season!) and the property felt intimate and uncrowded. The suites are bigger than most Airbnbs and the pool views are spectacular. Used our loyalty points for a free upgrade to a penthouse suite.",
        "review_date": "2026-01-08T10:12:00",
        "reviewer": "u/mediterranean_lover",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 145,
        "source_review_id": "rd_014",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "[r/scams] Is Karma Group a scam? My in-laws bought a membership and the cancellation clause is buried in 40 pages of fine print. They tried to cancel within the 'cooling off period' but were told they'd already used a benefit (a welcome drink at the resort!) so the period doesn't apply. Has anyone successfully cancelled and gotten a refund?",
        "review_date": "2025-12-18T23:40:00",
        "reviewer": "u/concerned_family_member",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 892,
        "source_review_id": "rd_015",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 4,
        "review_text": "[r/travel] Updated review of Karma Subito app (v2.3): They've improved the loading speed and the booking flow is slightly better. Still no dark mode and the search is meh, but at least it doesn't crash during checkout anymore. Progress, I guess? The new loyalty points dashboard is actually pretty nice.",
        "review_date": "2025-12-02T14:55:00",
        "reviewer": "u/app_review_guru",
        "country": "US",
        "language": "en",
        "app_version": "2.3",
        "helpful_count": 76,
        "source_review_id": "rd_016",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "[r/Bali] Karma Chakra in Ubud is perfect for a wellness retreat. The yoga pavilion overlooking the rice terraces is breathtaking. Did a 5-day detox programme and came back feeling completely renewed. The only downside is the resort is quite isolated — you definitely need a driver for anything off-property.",
        "review_date": "2025-11-15T07:20:00",
        "reviewer": "u/ubud_yoga_life",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 103,
        "source_review_id": "rd_017",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/india] Just discovered Karma Royal Haathi Mahal in South Goa and it's SO much better than the crowded North Goa resorts. The elephant-themed architecture is quirky and fun, the grounds are lush and green, and the pool is massive. Used the Karma membership for the first time and the check-in was seamless through the app.",
        "review_date": "2025-10-28T16:30:00",
        "reviewer": "u/goa_beyond_beaches",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 134,
        "source_review_id": "rd_018",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[r/assholedesign] Karma Subito app: You can't delete your account through the app. You have to EMAIL them to request deletion, then wait 30 days, then they send you a confirmation link that expires in 24 hours. Miss it and you have to start over. Classic dark pattern.",
        "review_date": "2025-10-10T21:05:00",
        "reviewer": "u/dark_pattern_hunter",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 567,
        "source_review_id": "rd_019",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[r/luxurytravel] Karma Baviera in the Italian Dolomites — where has this place been all my life? Stayed in December for the Christmas markets and it was pure magic. Log fires, mulled wine, snow-capped mountains, and the most comfortable beds I've slept in. Already booked our return trip for next winter through the app.",
        "review_date": "2025-09-22T11:45:00",
        "reviewer": "u/alpine_luxury",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 198,
        "source_review_id": "rd_020",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[r/travel] Karma Cay Tre in Vietnam — decent beachfront property but felt a bit dated compared to newer resorts in the area. The staff were wonderful and the seafood BBQ night was incredible. Would stay again but at a lower price point. The app couldn't process my Vietnamese credit card so had to use an international one.",
        "review_date": "2025-09-05T13:18:00",
        "reviewer": "u/vietnam_explorer",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 67,
        "source_review_id": "rd_021",
    },
    {
        "source": "Reddit",
        "app_name": "Karma Subito",
        "rating": 4,
        "review_text": "[r/travel] Suggestion for Karma Subito app: please add a 'Recently Viewed' section and a wishlist/favorites feature. I was comparing 4 different properties and had to keep navigating back to the search results because there's no way to save or bookmark. Basic stuff that every travel app has.",
        "review_date": "2025-08-20T18:33:00",
        "reviewer": "u/product_feedback_guy",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "rd_022",
    },
]
