"""
Social media review source (stub with realistic sample data).
Simulates combined LinkedIn, Facebook, and Twitter/X mentions of Karma Group.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class SocialMediaSource(BaseSource):
    """Returns realistic sample social media mentions for Karma Group."""

    @property
    def source_name(self) -> str:
        return "Social Media"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info(
            "SocialMediaSource: loaded %d sample reviews", len(self._reviews)
        )
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[LinkedIn] Just wrapped up an incredible leadership retreat at Karma Kandara, Bali 🌊 The resort provided a perfect blend of luxury and inspiration for our executive team. The private villas, cliff-edge meeting spaces, and world-class dining elevated our strategy sessions. Kudos to the Karma events team for flawless execution. #LeadershipRetreat #KarmaGroup #ExecutiveTravel",
        "review_date": "2026-07-03T08:30:00",
        "reviewer": "Rohit Malhotra, CEO at TechVista",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 234,
        "source_review_id": "sm_001",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 1,
        "review_text": "[Twitter/X] @KarmaGroupHQ your Karma Subito app is broken AGAIN. Tried to book 3 times today and the payment page keeps timing out. This is the 4th time in 2 months. I'm a paying member — please fix your tech stack. 🤦‍♂️ #KarmaSubito #BrokenApp",
        "review_date": "2026-06-25T19:45:00",
        "reviewer": "@frustrated_traveler",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "sm_002",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Facebook] Just had the most magical 40th birthday celebration at Karma Kandara! 🎂🌅 The team organized a surprise sunset dinner on the cliff edge with our closest friends. The food, the views, the service — everything was absolutely perfect. If you're looking for a venue for a milestone celebration, this is THE place. Thank you Karma Kandara for making my birthday unforgettable! 📸✨",
        "review_date": "2026-06-12T14:20:00",
        "reviewer": "Jessica Wang",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 156,
        "source_review_id": "sm_003",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "[Twitter/X] @KarmaGroupHQ Still waiting for my refund from the cancelled booking in March. 3 months and counting. Your chatbot says 'processing' and your support email goes unanswered. Meanwhile Booking.com refunded my other cancellation in 48 hours. Do better. #CustomerService #KarmaGroup",
        "review_date": "2026-05-30T16:50:00",
        "reviewer": "@travel_complaints_uk",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 67,
        "source_review_id": "sm_004",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[LinkedIn] Thrilled to announce that Karma Group has been named 'Best Luxury Resort Group — Asia Pacific' at the 2026 World Luxury Awards 🏆 Having been a member for 5 years, I can personally attest that this recognition is well-deserved. The consistency of service across their portfolio of properties is remarkable. Congratulations to the entire Karma team! #Luxury #HospitalityExcellence",
        "review_date": "2026-05-18T10:15:00",
        "reviewer": "Diana Foster, Hospitality Consultant",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 312,
        "source_review_id": "sm_005",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 3,
        "review_text": "[Twitter/X] Downloaded Karma Subito to check out their resorts. The app design is… okay? Property photos are gorgeous but the UX feels like 2019. No dark mode, no biometric login, the search filters are basic. It works but it's not in the same league as Hilton Honors or IHG. Could be so much better with some investment in the digital experience.",
        "review_date": "2026-05-05T21:30:00",
        "reviewer": "@digital_nomad_sarah",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 45,
        "source_review_id": "sm_006",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Facebook] Our family reunion at Karma Kandara was absolutely spectacular! 👨‍👩‍👧‍👦 16 family members across 4 villas for a week. The kids club kept the little ones busy while the adults relaxed by the pool. The Balinese cooking class and temple visit were highlights for everyone. Already planning next year's reunion! The Karma membership made it surprisingly affordable for the whole clan.",
        "review_date": "2026-04-22T12:40:00",
        "reviewer": "The Patel Family",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 203,
        "source_review_id": "sm_007",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "[Twitter/X] THREAD: My nightmare experience with Karma Group membership cancellation 🧵 1/ Bought membership in Jan, tried to cancel within 14-day cooling period 2/ App has NO cancellation button 3/ Emailed — got auto-reply saying '10 business days' 4/ Called — 55 min hold time 5/ Still no cancellation after 6 weeks 6/ Had to involve consumer protection. Avoid! #ConsumerRights",
        "review_date": "2026-04-08T18:55:00",
        "reviewer": "@consumer_advocate_oz",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 534,
        "source_review_id": "sm_008",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "[LinkedIn] Just returned from Karma Minoan in Crete where we hosted our company's annual offsite. The resort provided excellent meeting facilities and the team-building activities organized by Karma were creative and engaging. The only hiccup was the unreliable wifi during our presentation sessions. For corporate retreats, I'd recommend requesting a dedicated connection. #CorporateRetreat #Crete",
        "review_date": "2026-03-25T09:10:00",
        "reviewer": "Mark Stevens, VP Operations at DataFlow",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 78,
        "source_review_id": "sm_009",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[Twitter/X] @KarmaGroupHQ Feature request: PLEASE add an AI concierge to the Karma Subito app. The current chatbot is basically a FAQ page that pretends to be intelligent. I asked it 'What's the best time to visit Bali?' and it replied 'Please contact our reservations team.' 🤖💀 Even ChatGPT would do a better job.",
        "review_date": "2026-03-10T15:25:00",
        "reviewer": "@ai_product_person",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 156,
        "source_review_id": "sm_010",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Facebook] Can't stop thinking about the spa experience at Karma Kandara 💆‍♀️ The Balinese massage overlooking the ocean was genuinely life-changing. The therapist was incredibly skilled and the setting — perched on a cliff with the sound of waves below — was otherworldly. If you visit Bali, this spa treatment is non-negotiable. Book through the app, it's 15% cheaper than walk-in!",
        "review_date": "2026-02-25T20:05:00",
        "reviewer": "Nina Alexandrova",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "sm_011",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[LinkedIn] Interesting case study: Karma Group's digital transformation journey. As a hospitality tech consultant, I see massive potential in their resort portfolio but their app (Karma Subito) is lagging behind competitors. Key gaps: no dynamic pricing display, no AI-powered recommendations, basic loyalty dashboard. With the right tech investment, they could be a market leader. #HospitalityTech #DigitalTransformation",
        "review_date": "2026-02-12T11:35:00",
        "reviewer": "Aisha Patel, Hospitality Tech Advisor",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 245,
        "source_review_id": "sm_012",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Rottnest",
        "rating": 5,
        "review_text": "[Facebook] Best birthday present to myself — a solo retreat at Karma Rottnest Island 🏝️ Three days of cycling, snorkeling, reading, and quokka selfies. The eco-luxury concept is executed brilliantly. No cars, minimal noise, just pure nature and beautiful accommodation. The stargazing from the deck was incredible. Fully recharged! ⭐",
        "review_date": "2026-01-28T16:45:00",
        "reviewer": "Kate Morrison",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 134,
        "source_review_id": "sm_013",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "[Twitter/X] Warning to anyone considering Karma Group membership: the 'flexible exchange' they promise is anything but. Tried to swap my week at one property for another — told it wasn't possible because of 'seasonal demand.' But the property I wanted was showing availability on the app for non-members! How is that fair? #TimeshareProblems",
        "review_date": "2026-01-15T23:10:00",
        "reviewer": "@disappointed_member",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 289,
        "source_review_id": "sm_014",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 4,
        "review_text": "[LinkedIn] Kudos to the Karma Group tech team — the latest update to Karma Subito (v2.4) has noticeably improved performance. Page load times are faster and the booking flow is smoother. Still needs work on the search and discovery features, but moving in the right direction. Would love to see them invest in a proper digital wallet and family profile system next. #ProductDevelopment",
        "review_date": "2025-12-30T13:20:00",
        "reviewer": "Chris O'Connor, Product Manager",
        "country": "AU",
        "language": "en",
        "app_version": "2.4",
        "helpful_count": 67,
        "source_review_id": "sm_015",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[Facebook] Our honeymoon at Karma Song Hoai in Hoi An and Karma Kandara in Bali was the trip of a lifetime! 🥂💕 Two weeks of pure romance across two stunning properties. The staff at both resorts made us feel like royalty. The floating breakfast, the private dinners, the spa — every moment was perfect. Thank you Karma for starting our married life in style!",
        "review_date": "2025-12-18T19:50:00",
        "reviewer": "James & Sophie Miller",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 178,
        "source_review_id": "sm_016",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "[Twitter/X] @KarmaGroupHQ your app just charged me twice for a spa booking. That's $240 USD double-charged. Support ticket raised 5 days ago — no response. I can see both charges on my credit card statement. This is the kind of thing that makes people leave bad reviews. Please fix ASAP! #DoubleCharged #PaymentBug",
        "review_date": "2025-12-05T10:40:00",
        "reviewer": "@bali_holiday_gone_wrong",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 112,
        "source_review_id": "sm_017",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Kandara",
        "rating": 4,
        "review_text": "[Facebook] Wonderful yoga retreat at Karma Kandara! 🧘‍♀️ The morning sessions on the cliff-top deck with ocean views were transformative. The instructor was excellent and the resort's wellness menu was delicious and nourishing. Only wish the app had a wellness programme scheduler so I could plan sessions in advance instead of checking the board in the lobby every morning.",
        "review_date": "2025-11-22T07:15:00",
        "reviewer": "Maria Chen",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 56,
        "source_review_id": "sm_018",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[LinkedIn] Attended a Karma Group membership presentation out of curiosity. The properties look stunning and the concept of exchangeable holiday weeks across global resorts is appealing. However, the pricing structure is opaque and the sales team couldn't clearly explain the total cost of ownership over 10 years. Transparency would go a long way toward building trust. #HospitalityIndustry #Transparency",
        "review_date": "2025-11-08T14:30:00",
        "reviewer": "David Park, Finance Director",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 145,
        "source_review_id": "sm_019",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[Facebook] Just renewed our Karma membership for another 5 years! 🎉 After 12 holidays across 6 properties, we can honestly say it's the best investment we've made for our family. The kids have grown up visiting Karma resorts and now have incredible travel memories. From Bali to Bavaria, every trip has been special. Here's to 5 more years of Karma holidays! 🌏",
        "review_date": "2025-10-25T18:05:00",
        "reviewer": "The Henderson Family",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 201,
        "source_review_id": "sm_020",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 1,
        "review_text": "[Twitter/X] Dear @KarmaGroupHQ — your app doesn't support screen readers. As a visually impaired traveler, I literally cannot use Karma Subito. Buttons aren't labeled, images have no alt text, and the booking forms are completely inaccessible. This is a basic accessibility requirement. Please prioritize #a11y. #AccessibilityMatters #InclusiveDesign",
        "review_date": "2025-10-10T11:55:00",
        "reviewer": "@accessible_travel",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 456,
        "source_review_id": "sm_021",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Baviera",
        "rating": 5,
        "review_text": "[Facebook] Christmas in the Dolomites at Karma Baviera was a fairy tale come true! 🎄❄️ Fresh snow, mulled wine by the fireplace, the most adorable Christmas market in the village nearby, and gourmet holiday dinners. The kids built snowmen while we relaxed in the heated outdoor pool with mountain views. Already booking next Christmas through the app! 🏔️",
        "review_date": "2025-09-28T09:40:00",
        "reviewer": "Anna Schmidt",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 167,
        "source_review_id": "sm_022",
    },
    {
        "source": "Social Media",
        "app_name": "Karma Subito",
        "rating": 3,
        "review_text": "[Twitter/X] Karma Subito app idea: add a digital wallet feature so members can store their membership card, room keys, and resort credits all in one place. Currently I'm carrying a physical membership card, printing booking confirmations, and manually tracking my points. It's 2025 — everything should be in the app! #FeatureRequest #DigitalWallet",
        "review_date": "2025-09-12T16:20:00",
        "reviewer": "@tech_forward_traveler",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 198,
        "source_review_id": "sm_023",
    },
]
