"""
TripAdvisor review source (stub with realistic sample data).
Simulates hotel/resort reviews mentioning booking process and app usage.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class TripAdvisorSource(BaseSource):
    """Returns realistic sample TripAdvisor reviews for Karma Group resorts."""

    @property
    def source_name(self) -> str:
        return "TripAdvisor"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info("TripAdvisorSource: loaded %d sample reviews", len(self._reviews))
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Unbelievable cliff-edge location. The inclinator ride down to Nammos Beach is an experience in itself. Staff are attentive without being intrusive. Pre-booked our spa treatments via the Karma Subito app and the whole process was seamless. Best resort in Bali, hands down.",
        "review_date": "2026-07-01T10:23:00",
        "reviewer": "TravelJunkie_Sydney",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 18,
        "source_review_id": "ta_001",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 2,
        "review_text": "The resort is beautiful but showing its age in some villas. Our bathroom had mould in the grout and the air-con was noisy. Tried to raise a complaint through the app's chatbot and it just kept saying 'a team member will contact you shortly' — nobody ever did. Had to walk to reception.",
        "review_date": "2026-06-18T14:50:00",
        "reviewer": "HonestTraveler_UK",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 31,
        "source_review_id": "ta_002",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Royal Jimbaran",
        "rating": 5,
        "review_text": "We stayed in a two-bedroom villa and it was perfect for our family of four. The kids' pool area is fantastic and the kids' club kept them busy for hours. Private plunge pool was the icing on the cake. Used the Karma membership points for an upgrade — brilliant value.",
        "review_date": "2026-06-05T08:17:00",
        "reviewer": "FamilyTravellerDelhi",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 14,
        "source_review_id": "ta_003",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "DO NOT FALL FOR THE TIMESHARE PITCH. We were invited to a 'complimentary lunch' which turned out to be a 3-hour hard-sell presentation. When we declined, the sales person became visibly rude. Completely ruined day 2 of our holiday. The resort itself is nice but this practice is unacceptable.",
        "review_date": "2026-05-23T19:35:00",
        "reviewer": "NeverAgain_Perth",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 67,
        "source_review_id": "ta_004",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Royal Sanur",
        "rating": 4,
        "review_text": "Lovely beachfront location and the staff are genuinely warm. Rooms are spacious with a kitchenette which was handy for making kids' snacks. The only letdown was the app — tried to book a sunset dinner cruise and the booking form kept resetting when I selected the date. Eventually gave up and booked at reception.",
        "review_date": "2026-05-08T11:42:00",
        "reviewer": "SunshineFamily_Melb",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 9,
        "source_review_id": "ta_005",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Minoan",
        "rating": 5,
        "review_text": "Crete is magical and Karma Minoan is the perfect base. The suites are enormous with full kitchens. The pool area is gorgeous and never felt crowded even at peak season. Staff arranged a private boat trip that was the highlight of our Greek holiday. Highly recommended!",
        "review_date": "2026-04-22T16:08:00",
        "reviewer": "LuxeExplorer_London",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 22,
        "source_review_id": "ta_006",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Baviera",
        "rating": 4,
        "review_text": "Beautiful alpine setting in the Dolomites. Rooms were comfortable and the restaurant served excellent regional cuisine. The only issue was poor mobile connectivity which meant the Karma Subito app was basically unusable. They should add offline functionality for properties in remote locations.",
        "review_date": "2026-04-10T09:55:00",
        "reviewer": "AlpineAdventures",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 7,
        "source_review_id": "ta_007",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Rottnest",
        "rating": 5,
        "review_text": "What a unique property! Staying on Rottnest Island surrounded by quokkas and pristine beaches — it doesn't get more Australian than this. The eco-friendly focus is genuine, not just greenwashing. Used points from our Karma membership for a free night which made it even sweeter.",
        "review_date": "2026-03-28T12:30:00",
        "reviewer": "PerthLocal_Katie",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 16,
        "source_review_id": "ta_008",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Royal Haathi Mahal",
        "rating": 3,
        "review_text": "Good but not great. The Goan property has potential but housekeeping was inconsistent during our 5-night stay. Some days the room was spotless, other days the towels weren't replaced. The buffet breakfast is generous though. App payment kept failing — had to use my credit card at the desk.",
        "review_date": "2026-03-14T15:22:00",
        "reviewer": "MumbaiWeekender",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 11,
        "source_review_id": "ta_009",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Second visit to Karma Kandara and it's even better than I remembered. The new wellness programme is outstanding — did a week of yoga and meditation with daily spa treatments. The beach club has been refreshed and the cocktail menu is excellent. This is what luxury should feel like.",
        "review_date": "2026-02-26T18:45:00",
        "reviewer": "WellnessWanderer",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 20,
        "source_review_id": "ta_010",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Song Hoai",
        "rating": 4,
        "review_text": "Charming boutique property in the heart of Hoi An. The lantern-lit courtyard is stunning. Rooms are compact but well-designed. Walking distance to the old town and the night market. Great value for the location. The only thing missing was a proper in-app map showing nearby attractions.",
        "review_date": "2026-02-10T07:18:00",
        "reviewer": "BackpackerToLuxury",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 8,
        "source_review_id": "ta_011",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "Overpriced and overhyped. For the nightly rate I expected perfection but got lukewarm food, slow service, and a villa that smelled damp. The app shows beautiful photos that don't match reality. When I left a negative review on the app it never appeared. Suspicious.",
        "review_date": "2026-01-28T21:03:00",
        "reviewer": "DisappointedInBali",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 45,
        "source_review_id": "ta_012",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Salak",
        "rating": 5,
        "review_text": "Hidden gem near Bogor! The natural hot springs are incredible and the mountain air is so refreshing. The resort has a wonderful old-world colonial charm. Staff served us afternoon tea on the veranda overlooking the gardens. A perfect weekend escape from Jakarta.",
        "review_date": "2026-01-12T13:40:00",
        "reviewer": "JakartaEscapee",
        "country": "ID",
        "language": "en",
        "app_version": None,
        "helpful_count": 12,
        "source_review_id": "ta_013",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 3,
        "review_text": "Mixed experience. The location and views are 10/10 but the F&B is overpriced even by resort standards. A simple pasta was $28 USD. The app should show menu prices and let you order room service directly — currently you have to call the front desk. In 2026 that feels very outdated.",
        "review_date": "2025-12-30T16:55:00",
        "reviewer": "FoodieNomad",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 19,
        "source_review_id": "ta_014",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Royal Jimbaran",
        "rating": 5,
        "review_text": "Our 4th Karma property and possibly our favourite. The Jimbaran location gives you the best of both worlds — resort tranquillity with Bali nightlife a short ride away. The butler service was exceptional. Booking through Karma Subito with our accumulated loyalty points made it incredibly affordable.",
        "review_date": "2025-12-15T09:28:00",
        "reviewer": "LoyalKarmaFan",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 10,
        "source_review_id": "ta_015",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "The concept is good but the app experience lets it down badly. Couldn't complete my booking because the country dropdown kept defaulting back to 'Afghanistan' (first alphabetically) every time I scrolled down to select India. Had to book on the desktop website instead. Fix basic UX please.",
        "review_date": "2025-11-28T20:12:00",
        "reviewer": "TechSavvyTraveler",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 36,
        "source_review_id": "ta_016",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Cay Tre",
        "rating": 4,
        "review_text": "Peaceful beachfront resort in Phu Quoc. The sunsets here are otherworldly. Rooms are clean and comfortable. The Vietnamese cuisine at the resort restaurant is authentically prepared. Would love to see the app offer local experience bookings — cooking classes, market tours, etc.",
        "review_date": "2025-11-10T11:47:00",
        "reviewer": "VietnamDreamer",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 5,
        "source_review_id": "ta_017",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Honeymoon perfection! The private villa with ocean views, the floating breakfast, the couples spa treatment overlooking the cliff — every moment was magical. The Karma team even arranged a surprise anniversary cake. We'll be back for every milestone.",
        "review_date": "2025-10-25T14:15:00",
        "reviewer": "Newlyweds_2025",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 25,
        "source_review_id": "ta_018",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "The app is borderline non-functional. Every time I try to access my past booking history it shows a blank screen. My loyalty points balance hasn't updated in 3 months. The chatbot is useless and there's no way to speak to a real person through the app. Just give me a phone number!",
        "review_date": "2025-10-08T22:33:00",
        "reviewer": "FrustratedMember",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 42,
        "source_review_id": "ta_019",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Baviera",
        "rating": 4,
        "review_text": "Spent Christmas week at Karma Baviera with the extended family and it was a magical winter wonderland. The mulled wine by the fireplace, the snowy mountain views, the cozy rooms — perfect. Would be 5 stars if the app allowed group bookings for large families without creating separate reservations.",
        "review_date": "2025-09-20T10:05:00",
        "reviewer": "ChristmasInTheAlps",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 13,
        "source_review_id": "ta_020",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Royal Sanur",
        "rating": 3,
        "review_text": "Decent resort but not luxury. More like a well-maintained apartment complex with a nice pool. Good for families on a budget who want to self-cater. The location on Sanur beach is the biggest draw. App keeps logging me out every time I switch between properties — annoying.",
        "review_date": "2025-09-05T17:40:00",
        "reviewer": "BudgetLuxury_Seeker",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 8,
        "source_review_id": "ta_021",
    },
    {
        "source": "TripAdvisor",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "Returned to Karma Kandara after 3 years and they've significantly improved the food offerings. The new Mediterranean restaurant is excellent. The kids club has expanded and our 6-year-old didn't want to leave. Seamless booking through the updated app. Will definitely be back.",
        "review_date": "2025-08-18T08:22:00",
        "reviewer": "ReturnVisitor_Perth",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 11,
        "source_review_id": "ta_022",
    },
]
