"""
Trustpilot review source (stub with realistic sample data).
Simulates reviews about Karma Group resorts, membership programme, and booking experience.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class TrustpilotSource(BaseSource):
    """Returns realistic sample Trustpilot reviews for Karma Group."""

    @property
    def source_name(self) -> str:
        return "Trustpilot"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info("TrustpilotSource: loaded %d sample reviews", len(self._reviews))
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "We stayed at Karma Kandara for our 10th anniversary and it was absolutely magical. The infinity pool overlooking the Indian Ocean is jaw-dropping. Staff remembered our names from day one. The Karma Subito app made checking in a breeze — no queues at all.",
        "review_date": "2026-06-28T09:14:00",
        "reviewer": "Sarah M.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 12,
        "source_review_id": "tp_001",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "Terrible experience trying to book through the Karma Subito app. The booking calendar kept showing dates that were already full, and when I finally selected available dates the form lost all my data and I had to start over. Ended up calling the resort directly which took 40 minutes on hold.",
        "review_date": "2026-06-15T17:32:00",
        "reviewer": "James K.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 34,
        "source_review_id": "tp_002",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Been a Karma member for 6 years now and it keeps getting better. The rewards programme is genuinely useful — redeemed points for a 3-night stay at Karma Rottnest. The new app is a huge improvement over the old website.",
        "review_date": "2026-06-02T11:05:00",
        "reviewer": "Priya D.",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 8,
        "source_review_id": "tp_003",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "The resort itself is lovely but the membership sales pitch was incredibly aggressive. We felt pressured during what was supposed to be a relaxing holiday. The app's concierge chatbot gave generic responses and couldn't answer specific questions about our membership benefits.",
        "review_date": "2026-05-20T14:18:00",
        "reviewer": "David & Claire R.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 27,
        "source_review_id": "tp_004",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "Karma Royal Jimbaran exceeded expectations. Beautiful villa, private pool, outstanding Balinese hospitality. Only complaint is the spa booking through the app — the dropdown menus for selecting treatments are clunky and don't show availability until you go through 4 screens.",
        "review_date": "2026-05-11T08:44:00",
        "reviewer": "Ling W.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 5,
        "source_review_id": "tp_005",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Third time staying at Karma Baviera and every visit has been perfect. The alpine setting, the food, and the warm staff make it a family favourite. Booked entirely through Karma Subito this time — so much easier than last year.",
        "review_date": "2026-04-29T10:21:00",
        "reviewer": "Marco T.",
        "country": "IT",
        "language": "en",
        "app_version": None,
        "helpful_count": 3,
        "source_review_id": "tp_006",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "Payment processing on the app is a nightmare. I was charged twice for my deposit and it took 3 weeks and 7 emails to get a refund. Their customer support kept passing me between departments. Marriott app never does this to me.",
        "review_date": "2026-04-17T22:09:00",
        "reviewer": "Angela P.",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 41,
        "source_review_id": "tp_007",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "Mixed feelings. Karma Chakra in Bali was stunning but the app crashed multiple times when I tried to book excursions. Had to go to the front desk instead. The property itself is five stars but the tech side needs serious work.",
        "review_date": "2026-04-05T15:37:00",
        "reviewer": "Robert S.",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 14,
        "source_review_id": "tp_008",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Absolutely love the Karma membership. We've now visited 5 different properties across 3 countries. The kids club at Karma Royal Sanur kept our children entertained while we had spa time. Worth every penny of the membership fee.",
        "review_date": "2026-03-22T12:50:00",
        "reviewer": "Meena & Raj S.",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 19,
        "source_review_id": "tp_009",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "The app needs a dark mode — using it at night while in bed hurts my eyes. Also the search is terrible. I typed 'Bali' and got results for Bavaria. How is that even possible? Wish it was as easy as Airbnb to find and book properties.",
        "review_date": "2026-03-10T20:15:00",
        "reviewer": "Tom H.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 22,
        "source_review_id": "tp_010",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "Great resort experience at Karma Salak. The hot springs were incredible and the food was authentic Indonesian cuisine done perfectly. Only 4 stars because check-in took forever — the staff were manually entering our details even though we'd filled everything in the app.",
        "review_date": "2026-02-28T07:33:00",
        "reviewer": "Yuki N.",
        "country": "JP",
        "language": "en",
        "app_version": None,
        "helpful_count": 6,
        "source_review_id": "tp_011",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "The spa at Karma Kandara is world-class. My wife and I did the couples' package and it was the highlight of our Bali trip. The cliff-top setting is extraordinary. Used the app to book the treatment and got a 15% member discount automatically applied.",
        "review_date": "2026-02-14T16:42:00",
        "reviewer": "Daniel F.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 9,
        "source_review_id": "tp_012",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "Beware of the membership upsell. What started as a 'quick 30-minute presentation' turned into 2.5 hours of high-pressure sales tactics. When we said no, they sent us 4 follow-up emails. The app keeps pushing membership upgrade notifications too. Very off-putting.",
        "review_date": "2026-02-01T13:28:00",
        "reviewer": "Karen L.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 53,
        "source_review_id": "tp_013",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "The property at Karma Cay Tre in Vietnam was beautiful but dated. Rooms could use a refresh. The app didn't have an offline mode so when our wifi was patchy we couldn't access our booking details. Would love to see offline booking confirmations stored locally.",
        "review_date": "2026-01-18T09:55:00",
        "reviewer": "Chris M.",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 11,
        "source_review_id": "tp_014",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Just back from Karma Minoan in Crete and it was perfection. The suites are spacious, the beach is pristine, and the staff go above and beyond. Easily the best timeshare-style programme we've been part of. The rewards points system is transparent and generous.",
        "review_date": "2026-01-05T11:12:00",
        "reviewer": "Natasha B.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 15,
        "source_review_id": "tp_015",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "Feature request: family profiles. I travel with my wife and two kids and every time I book I have to re-enter everyone's passport details. The app should let me save family member profiles like most airline apps do.",
        "review_date": "2025-12-20T18:06:00",
        "reviewer": "Arjun P.",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 30,
        "source_review_id": "tp_016",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Karma Song Hoai in Hoi An is a hidden gem. The lantern-lit streets, the tailored experiences, and the rooftop bar made this our favourite holiday ever. Booked through the app and everything went smoothly from start to finish.",
        "review_date": "2025-12-08T14:30:00",
        "reviewer": "Emily C.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 7,
        "source_review_id": "tp_017",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "App is incredibly slow on my Android phone. Takes 15+ seconds to load property pages and images don't load half the time. I've got a Galaxy S24 so it's not my phone. Club Mahindra's app runs circles around this.",
        "review_date": "2025-11-25T21:44:00",
        "reviewer": "Vikram J.",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 18,
        "source_review_id": "tp_018",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "Average overall. The resort was nice but not luxury-tier given the price. Felt more like a 4-star than 5-star. The digital wallet feature in the app would be great — right now I have to carry my membership card everywhere because the app QR doesn't always scan at reception.",
        "review_date": "2025-11-10T10:22:00",
        "reviewer": "Sophie A.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 9,
        "source_review_id": "tp_019",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "We're on our 8th Karma holiday and still loving it. The consistency across properties is impressive — whether Bali, Greece, or India, the Karma experience is always top-notch. Staff are the real differentiator. An AI concierge feature in the app would be the cherry on top!",
        "review_date": "2025-10-30T08:17:00",
        "reviewer": "Greg & Lisa W.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 11,
        "source_review_id": "tp_020",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 4,
        "review_text": "Lovely stay at Karma Rottnest Island. The quokkas were the highlight for the kids! Only gripe: the app notification system is broken — I signed up for check-in reminders but never received any. Had to set my own phone alarms.",
        "review_date": "2025-10-14T13:05:00",
        "reviewer": "Hannah K.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 4,
        "source_review_id": "tp_021",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "Disappointed with the web booking experience. The property photos on the app are clearly professional shoots from years ago — when we arrived the rooms looked quite different. Misleading. Also, no way to filter properties by pet-friendly or accessibility options.",
        "review_date": "2025-09-28T16:50:00",
        "reviewer": "Martin D.",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 23,
        "source_review_id": "tp_022",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "Karma Royal Haathi Mahal in Goa is paradise. The elephant statues, the lush grounds, the pool — everything is Instagram-perfect. The buffet breakfast alone is worth staying. Used Karma Subito to book and the whole process took under 5 minutes.",
        "review_date": "2025-09-12T07:38:00",
        "reviewer": "Sanjay M.",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 16,
        "source_review_id": "tp_023",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "The concept is great but execution is inconsistent. Our experience at one Bali property was amazing but another felt neglected. The app should show recent guest reviews for each property so you know what you're booking — right now it only shows the marketing blurb.",
        "review_date": "2025-08-29T19:14:00",
        "reviewer": "Rachel F.",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 20,
        "source_review_id": "tp_024",
    },
    {
        "source": "Trustpilot",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "We just renewed our Karma membership for another 5 years. The value is unbeatable when you use it regularly. Points exchange flexibility has improved dramatically. The new Karma Subito app is a game-changer for last-minute bookings.",
        "review_date": "2025-08-15T12:00:00",
        "reviewer": "Paul & Janet H.",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 7,
        "source_review_id": "tp_025",
    },
]
