"""
YouTube comment source (stub with realistic sample data).
Simulates YouTube comments from travel vlogs and review videos about Karma Group.
"""
import logging
from typing import List, Dict

from scrapers.base_source import BaseSource

logger = logging.getLogger(__name__)


class YouTubeSource(BaseSource):
    """Returns realistic sample YouTube comments about Karma Group resorts."""

    @property
    def source_name(self) -> str:
        return "YouTube"

    @property
    def is_live(self) -> bool:
        return False

    def fetch_reviews(self) -> List[Dict]:
        self._reviews = _SAMPLE_REVIEWS
        logger.info("YouTubeSource: loaded %d sample reviews", len(self._reviews))
        return self._reviews


_SAMPLE_REVIEWS: List[Dict] = [
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Comment on: 'KARMA KANDARA BALI — Full Resort Tour 2026'] This place is INSANE. Just watched your whole video and immediately booked through the Karma Subito app. The cliff-top pool looks even better than you showed. Can't wait for our trip in August! Thanks for the amazing review 🔥🌊",
        "review_date": "2026-06-29T14:22:00",
        "reviewer": "TravelWithTom",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 45,
        "source_review_id": "yt_001",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 1,
        "review_text": "[Comment on: 'Honest Review — Is Karma Kandara Worth The Hype?'] I stayed here last month and your video is way too kind. You didn't mention the aggressive timeshare pitches, the overpriced minibar ($8 for a bottle of water!), or the fact that the wifi barely works. Beautiful location but the experience is let down by nickel-and-diming guests. Also the Karma app is basically unusable — crashed 3x during my stay.",
        "review_date": "2026-06-18T09:45:00",
        "reviewer": "RealTalkTravel",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 123,
        "source_review_id": "yt_002",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[Comment on: 'Top 10 Luxury Resorts in Bali 2026'] So happy you included Karma Kandara! We've been members for years and it's genuinely one of the best resorts in Bali. The private beach is unreal and the spa is world-class. Great video! 🙌",
        "review_date": "2026-06-05T16:30:00",
        "reviewer": "LuxuryLifestyleLisa",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 67,
        "source_review_id": "yt_003",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[Comment on: 'Karma Subito App — Is It Any Good?'] Thanks for the honest app review. I had the EXACT same issues — the booking calendar bug where you select dates and it jumps back to the current month is infuriating. And yes, the country dropdown problem is real. Had to scroll through 200+ countries because there's no search. It's 2026, this is basic UX. 😤",
        "review_date": "2026-05-22T11:55:00",
        "reviewer": "AppReviewPro",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "yt_004",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Rottnest",
        "rating": 5,
        "review_text": "[Comment on: 'Rottnest Island — Hidden Gem Near Perth'] OMG the Karma Rottnest glamping looks incredible!! I'm from Perth and had no idea this existed. The quokka footage at 3:42 made my day 😍 Booking this for my husband's birthday. Is the eco tent really as nice as it looks in the video? Anyone been recently?",
        "review_date": "2026-05-10T20:15:00",
        "reviewer": "PerthMumAdventures",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 34,
        "source_review_id": "yt_005",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[Comment on: 'TIMESHARE EXPOSED — Are Karma Group Memberships A Scam?'] Great investigative video. I'm a Karma member and I have mixed feelings. The properties ARE beautiful and the points system works IF you use it regularly. But the sales tactics are predatory and the cancellation process is designed to be difficult. They need to modernize and be more transparent. The app needs a clear cancellation button.",
        "review_date": "2026-04-28T15:40:00",
        "reviewer": "InformedConsumer2026",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 234,
        "source_review_id": "yt_006",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Comment on: 'BALI HONEYMOON VLOG — 7 Days of Paradise'] You two are adorable! Karma Kandara was clearly the highlight of your trip. The private dinner on the cliff at sunset — WOW, my partner and I are now planning the exact same thing for our anniversary. Did you book the dinner through the app or through the resort directly? 💕",
        "review_date": "2026-04-15T18:08:00",
        "reviewer": "RomanceTravel_UK",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 56,
        "source_review_id": "yt_007",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Baviera",
        "rating": 4,
        "review_text": "[Comment on: 'Best Ski Resorts in the Dolomites'] Karma Baviera is indeed lovely! Stayed there last Christmas and the location is magical. The hotel isn't huge which gives it a cozy, intimate feel. The food was excellent. Only downside is the ski shuttle timing — it doesn't align with the lift opening hours. The app doesn't show shuttle schedules at all which would be super helpful.",
        "review_date": "2026-04-02T12:25:00",
        "reviewer": "SkiBumDave",
        "country": "DE",
        "language": "en",
        "app_version": None,
        "helpful_count": 28,
        "source_review_id": "yt_008",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 1,
        "review_text": "[Comment on: 'Why I'll NEVER Stay at a Timeshare Resort Again'] Your experience mirrors mine EXACTLY. Karma Group invited us for a 'complimentary lunch' and we ended up trapped in a sales room for 3 hours. The sales guy got hostile when we said no. It ruined our entire holiday. Their app keeps sending promotional notifications even after I unsubscribed. HOW IS THIS LEGAL.",
        "review_date": "2026-03-18T22:50:00",
        "reviewer": "TruthInTravel",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 345,
        "source_review_id": "yt_009",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Song Hoai",
        "rating": 5,
        "review_text": "[Comment on: 'HOI AN TRAVEL GUIDE — Hidden Gems You MUST Visit'] I'm staying at Karma Song Hoai right now watching this video from the rooftop bar! 😂 Can confirm everything you said — the location is perfect, the lantern-lit streets are magical at night, and the staff are incredibly friendly. The Vietnamese coffee served at breakfast is the best I've ever had. Hoi An is now my favorite place on earth ❤️",
        "review_date": "2026-03-05T08:30:00",
        "reviewer": "LiveFromVietnam",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 78,
        "source_review_id": "yt_010",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Subito",
        "rating": 3,
        "review_text": "[Comment on: 'Best Travel Apps 2026 — My Top 10'] Surprised you didn't mention Karma Subito. It's not great but not terrible either. The property browsing is nice (good photos) but the booking process is clunky. My main gripe: no offline mode. When you're at a remote resort with spotty wifi and can't pull up your booking confirmation, that's a problem. Even a simple PDF download of the confirmation would help.",
        "review_date": "2026-02-20T14:10:00",
        "reviewer": "TechTravelTips",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 42,
        "source_review_id": "yt_011",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Royal Haathi Mahal",
        "rating": 5,
        "review_text": "[Comment on: 'GOA BEYOND THE BEACHES — Luxury Resorts in South Goa'] Karma Royal Haathi Mahal is our family's annual Diwali destination! The elephant architecture is so cool and the kids love it. The pool complex is massive and never crowded. The staff put on incredible Diwali celebrations. Can't recommend it enough for families! 🐘🎆",
        "review_date": "2026-02-08T17:45:00",
        "reviewer": "MumbaiToGoa",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 56,
        "source_review_id": "yt_012",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 4,
        "review_text": "[Comment on: 'Karma Kandara — $500/Night Villa Tour'] Great video! The villa looks stunning. One thing you didn't mention — the food prices are steep even by resort standards. A margherita pizza was $22 and a basic cocktail was $18. For the nightly rate, they could include more. The Airbnb villa next door had similar views for 1/3 the price. Just saying. 🤷",
        "review_date": "2026-01-25T10:35:00",
        "reviewer": "BudgetLuxuryHacks",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 91,
        "source_review_id": "yt_013",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 5,
        "review_text": "[Comment on: 'Luxury Travel on a Budget — How We Travel 5-Star for Less'] Great tip about the Karma membership points! We've been doing this for years — buy the membership, accumulate points, and you can get stays at stunning resorts for a fraction of the rack rate. The key is using it at least 2-3 times per year. At that frequency the membership pays for itself easily. 💰✈️",
        "review_date": "2026-01-12T13:20:00",
        "reviewer": "SmartTravelCouple",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 134,
        "source_review_id": "yt_014",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Salak",
        "rating": 4,
        "review_text": "[Comment on: 'Weekend Getaways From Jakarta — Top 5 Picks'] Thanks for featuring Karma Salak! The hot springs in the rainforest setting are truly magical. I've been 3 times and it never gets old. The colonial buildings have so much character. Pro tip: request the room with the private hot spring tub on the balcony — it's incredible at night. The app sometimes glitches when booking this specific room type though.",
        "review_date": "2025-12-28T19:00:00",
        "reviewer": "JakartaExplorer",
        "country": "ID",
        "language": "en",
        "app_version": None,
        "helpful_count": 45,
        "source_review_id": "yt_015",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 2,
        "review_text": "[Comment on: 'AVOID THESE Travel Scams in Bali 2025'] While I wouldn't call Karma a 'scam' exactly, the high-pressure membership sales are uncomfortable. My wife and I attended the presentation because we were promised a free spa treatment. The presentation was 2 hours of hard selling and when we declined, the sales agent acted offended. We did get the spa treatment but it felt tainted. Their app chatbot pushes membership upgrades too.",
        "review_date": "2025-12-15T11:40:00",
        "reviewer": "HonestBaliGuide",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 178,
        "source_review_id": "yt_016",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Minoan",
        "rating": 5,
        "review_text": "[Comment on: 'CRETE TRAVEL VLOG — 2 Weeks in Greece'] Karma Minoan is GORGEOUS! We stayed there last summer and your footage brought back all the memories. The rooftop terrace with the view of the White Mountains 😍 And yes, the suites are huge — we had a full kitchen and living room. Perfect for families. Booked our return trip already! 🇬🇷",
        "review_date": "2025-12-02T15:55:00",
        "reviewer": "GreekIslandDreams",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 67,
        "source_review_id": "yt_017",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Subito",
        "rating": 2,
        "review_text": "[Comment on: 'Worst Hotel Booking Apps — My Rankings'] Karma Subito deserves a spot on this list. The app crashed on me during payment and I ended up with a pending charge but no confirmed booking. Had to call the resort directly to sort it out. Zero saved payment methods, no Apple Pay, no Google Pay. It's 2025 — even my local pizza shop accepts Apple Pay. Get with the times @KarmaGroup 🍕📱",
        "review_date": "2025-11-18T20:25:00",
        "reviewer": "AppCriticDaily",
        "country": "US",
        "language": "en",
        "app_version": None,
        "helpful_count": 156,
        "source_review_id": "yt_018",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Comment on: 'I Stayed at 10 Bali Resorts — Here's My Ranking'] Totally agree with Karma Kandara at #2! The only place that beats it IMO is the Four Seasons Jimbaran. But for the price difference, Karma is better value — especially with membership points. The beach club is elite and the spa is in the top 3 I've ever experienced globally. Stunning property! 🏆",
        "review_date": "2025-11-05T09:10:00",
        "reviewer": "GlobalLuxuryNomad",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 89,
        "source_review_id": "yt_019",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Group",
        "rating": 3,
        "review_text": "[Comment on: 'Timeshare vs Hotel — Which Is Better Value?'] Good balanced video! I've been a Karma member for 3 years and the math works out if you use it frequently. BUT the upfront cost is significant and the app makes managing your membership unnecessarily complicated. Points expiry notifications come AFTER your points expire. Who designed this system? Need better alerts and a simpler dashboard.",
        "review_date": "2025-10-20T14:35:00",
        "reviewer": "FinanceTraveler",
        "country": "IN",
        "language": "en",
        "app_version": None,
        "helpful_count": 112,
        "source_review_id": "yt_020",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Kandara",
        "rating": 5,
        "review_text": "[Comment on: 'Best Beach Clubs in Bali 2025'] The Karma Beach Club at Kandara is ABSOLUTELY in the top 3. The inclinator ride down the cliff is such a unique experience and the beach itself is pristine and uncrowded. The cocktails are pricey but well-made. The DJ sets on Saturday evenings are fire 🔥 This is peak Bali vibes!",
        "review_date": "2025-10-05T17:50:00",
        "reviewer": "BaliVibesOnly",
        "country": "AU",
        "language": "en",
        "app_version": None,
        "helpful_count": 78,
        "source_review_id": "yt_021",
    },
    {
        "source": "YouTube",
        "app_name": "Karma Subito",
        "rating": 4,
        "review_text": "[Comment on: 'Hotel App Tips — Getting the Best Deals'] Good tip about booking through Karma Subito for the member discount! I saved about 20% compared to the website price. The app UX is rough around the edges but if you can navigate through the clunky booking flow, the savings are real. Would love to see them add price comparison with OTAs so you can see the savings in real-time.",
        "review_date": "2025-09-18T12:15:00",
        "reviewer": "DealHunterMax",
        "country": "GB",
        "language": "en",
        "app_version": None,
        "helpful_count": 34,
        "source_review_id": "yt_022",
    },
]
